name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

# ---------- BUILD FRONTEND ----------

    - name: Build frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/contact-pri:contact-fe ./frontend

    - name: Push frontend image
      run: |
        docker push ${{ secrets.DOCKER_USER }}/contact-pri:contact-fe

# ---------- BUILD BACKEND ----------

    - name: Build backend image
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/contact-pri:contact-be ./backend

    - name: Push backend image
      run: |
        docker push ${{ secrets.DOCKER_USER }}/contact-pri:contact-be

    - name: Logout DockerHub
      run: docker logout

# ---------- DEPLOY ----------

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

          docker pull ${{ secrets.DOCKER_USER }}/contact-pri:contact-fe
          docker pull ${{ secrets.DOCKER_USER }}/contact-pri:contact-be

          cd /home/ubuntu/contact-pri

          docker stack deploy --detach=true -c stack.yml contact-app
